# Generated by Django 3.2.4 on 2021-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.SlugField(max_length=101, unique=True, verbose_name='Nombre clave'),
        ),
    ]
